import 'package:dreampuppy/src/features/pet_list/domain/entities/pet_card.dart';
import 'package:flutter/material.dart';

final suggestedCaracteristics = [
  'Pelo curto',
  'Pelo longo',
  'Pelo liso',
  'Pelo crespo',
  'Pelo duro',
  'Pelo ondulado',
  'Pelo encaracolado',
  'Pelo sedoso',
  'Pelo duplo',
  'Pelo semilongo',
  'Pelo semiduro',
  'Pelo semicurto',
  'Pelo semicrespo',
  'Pelo semiondulado',
  'Pelo semiliso',
  'Pelo semisedoso',
  'Pelo semiduplo',
  'Pelo semilongo',
  'Pelo semiduro',
  'Pelo semicurto',
  'Pelo semicrespo',
  'Pelo semiondulado',
  'Pelo semiliso',
  'Pelo semisedoso',
  'Pelo semiduplo',
  'Pelo semilongo',
  'Pelo semiduro',
  'Pelo semicurto',
  'Pelo semicrespo',
  'Pelo semiondulado',
  'Pelo semiliso',
  'Pelo semisedoso',
  'Pelo semiduplo',
  'Pelo semilongo',
  'Pelo semiduro',
  'Pelo semicurto',
  'Pelo semicrespo',
  'Pelo semiondulado',
  'Pelo semiliso',
  'Pelo semisedoso',
  'Pelo semiduplo',
  'Pelo semilongo',
  'Pelo semiduro',
  'Pelo semicurto',
  'Pelo semicrespo',
  'Pelo semiondulado',
  'Pelo semiliso',
  'Pelo semisedoso',
  'Pelo semiduplo',
  'Pelo semilongo',
  'Pelo semiduro',
  'Pelo semicurto',
  'Pelo semicrespo',
  'Pelo semiondulado',
  'Pelo semiliso',
  'Pelo semisedoso',
  'Pelo semiduplo',
  'Pelo semilongo',
  'Pelo semiduro',
  'Pelo semic'
];

final List<PetCardEntity> cards = [
  PetCardEntity(
      breed: "Golden Retriever",
      colorValue: Colors.orange[200]!.value,
      imgUrl: 'assets/images/dogs/cane_corso.png'),
  PetCardEntity(
      imgUrl: 'assets/images/dogs/rottweiler.png',
      breed: "Rottweiler",
      description:
          "Robust and powerful, the Rottweiler is happiest when given a job to perform. His intelligence, endurance and willingness to work make him suitable as a police dog, herder, service dog, therapy dog, obedience competitor and devoted companion.",
      colorValue: Colors.red[200]!.value),
  PetCardEntity(breed: "Shih xtzu", colorValue: Colors.blue[200]!.value),
  PetCardEntity(breed: "Shih xtzu", colorValue: Colors.blue[200]!.value),
  PetCardEntity(breed: "Shih xtzu", colorValue: Colors.blue[200]!.value),
  PetCardEntity(breed: "Spitz Alemão", colorValue: Colors.green[200]!.value),
  PetCardEntity(breed: "Labrador", colorValue: Colors.purple[200]!.value),
];
